### ISSUE TITLE
Added event handlers support

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/FluentLayout#2]
```csharp
new Button().SetClicked(OnClicked)
```
etc.

**Comment by Miiite** [comment]
I started to work on the event generation code (first results [visible here](https://github.com/Miiite/FluentLayout/blob/master/lib/FluentLayout/Codegen/ButtonExtensions.codegen.cs)), but I'm still wondering how to handle event unsubscription. Any ideas yet ?

**Comment by Miiite** [comment]
I'm looking into this stackoverflow post https://stackoverflow.com/questions/91778/how-to-remove-all-event-handlers-from-an-event to maybe add a "ClearEventHandlers" method on each of the VisualElements. Looks like we could add a "ClearEventHandlers" method to release any previously added event handler, but that uses a lot of reflection ...

**Comment by AndreiMisiukevich** [comment]
> I started to work on the event generation code (first results [visible here](https://github.com/Miiite/FluentLayout/blob/master/lib/FluentLayout/Codegen/ButtonExtensions.codegen.cs)), but I'm still wondering how to handle event unsubscription. Any ideas yet ?

we won't handle unsubscriptions (XAML + codebehind handlers do not, for example)

**Comment by Miiite** [comment]
XAML events unsubscription is handled for us when the layout is disposed. But in theory if you add an eventHandler in your page's codebehind, you should also remove that event handler when leaving the page. Since we'll be creating the event handlers ourselves, I'm not sure they will be disposed by the Framework when the view is disposed.
I'll try to look into that.
